### ISSUE TITLE
Feature: support scope name defined in variable

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco-keys-manager#80] opened 2021-02-03 16:01 UTC
```
const componentScope = 'scopeName';
const loader = scopeLoader(
  (lang, root) => import(`./${root}/${lang}.json`),
  componentScope
);

...

  providers: [
    TranslocoDatePipe,
    {
      provide: TRANSLOCO_SCOPE,
      useValue: {
        scope: componentScope,
        loader,
      },
    },
  ],
```

Causes scope name to be read as componentScope when creating folders

**Comment by shaharkazaz** [comment] 2021-03-11 08:49
@ChazUK Currently we don't support dynamic values, you are welcome to open a PR for it 🙂

**Comment by shaharkazaz** [comment] 2021-10-02 15:09
Duplicate of #42

**Closed by shaharkazaz** 2021-10-02 15:09 UTC
Labels: enhancement, PRs welcome
