### ISSUE TITLE
Bug  transloco.config.js rootTranslationsPath: is incorrect for i18n:find

### ISSUE THREAD

**Issue by fpmcguire51** [ngneat/transloco-keys-manager#90] opened 2021-04-18 18:29 UTC
### Current behavior
version: package.json  
"@ngneat/transloco": "^2.20.1",
"@ngneat/transloco-keys-manager": "^2.7.1",
CLI option

> npm run i18n:find results in 'Translations path path provided doesn't exists!'

### Expected behavior
Expect the display of a table listing missing keys as described in the documentation

### Steps To Reproduce
Install transloco
Install transloco-keys-manager (CLI option)
> npm run i18n:find

### transloco.config.js (as generated by transloco installation)
module.exports = {
  rootTranslationsPath: 'src/assets/i18n/',
  langs: ['en', 'de'],
  keysManager: {}
};

Should be:
module.exports = {
  rootTranslationsPath: '../src/assets/i18n/',
  langs: ['en', 'de'],
  keysManager: {}
};
### Environment
<pre><code>- Keys manager version: 2.7.1 
- Node version: 14.16.1
- Platform:  win32 x64
</code></pre>

### Contribution
I would like to make a pull request for this feature:
[ ] Yes! 🚀
[ ] Maybe next time

**Comment by mkubdev** [comment] 2021-07-26 08:59
Thanks!

**Comment by shaharkazaz** [comment] 2021-10-07 06:43
@fpmcguire51 So the issue is with the config generated by the CLI? is there a special structure to your project? can I reproduce this in a new Angular/NX workspace? (generated via their CLI)

**Comment by lukechi1219** [comment] 2021-11-03 09:00
> @fpmcguire51 So the issue is with the config generated by the CLI? is there a special structure to your project? can I reproduce this in a new Angular/NX workspace? (generated via their CLI)

@shaharkazaz I have this issue too. 

For "transloco-keys-manager find" to work, I just change transloco.config.js

from rootTranslationsPath: 'src/assets/i18n/',

to rootTranslationsPath: 'assets/i18n/',

but I don't know whether there is any side effect...

Angular CLI: 12.2.8
Node: 14.18.0
Package Manager: npm 7.24.2
OS: win32 x64

reproduce steps

1. ng new angular-transloco
2. cd angular-transloco
3. ng add @ngneat/transloco -> default en, es
4. ng g @ngneat/transloco:keys-manager -> CLI
5. npm run i18n:find

actual result:  Translations path provided doesn't exists!

expected result: Starting Search For Missing Keys

**Comment by shaharkazaz** [comment] 2022-01-22 08:56
The schematics are not part of this lib, fixed in this [commit](https://github.com/ngneat/transloco/commit/ce031c97da8fb9153e83422749484b3938082250)

**Closed by shaharkazaz** 2022-01-22 08:56 UTC
